export const ROUTE_TO_MAIN_CATEGORY_MASTER = "ROUTE_TO_MAIN_CATEGORY_MASTER";
export const ROUTE_TO_SUB_CATEGORY_MASTER = "ROUTE_TO_SUB_CATEGORY_MASTER";
export const ROUTE_TO_SAMPLE_CATEGORY_MASTER =
  "ROUTE_TO_SAMPLE_CATEGORY_MASTER";
export const ROUTE_TO_MATERIAL_TYPE = "ROUTE_TO_MATERIAL_TYPE";
