export const ROUTE_TO_PARAMETER_MASTER = "ROUTE_TO_PARAMETER_MASTER";
export const ROUTE_TO_MATERIAL_PARAMETER_MASTER =
  "ROUTE_TO_MATERIAL_PARAMETER_MASTER";
export const ROUTE_TO_EQUIPMENT_PARAMETER_MASTER =
  "ROUTE_TO_EQUIPMENT_PARAMETER_MASTER";
export const ROUTE_TO_TEST_PARAMETER_MASTER = "ROUTE_TO_TEST_PARAMETER_MASTER";
export const ROUTE_TO_ADDITIONAL_PARAMETER_MASTER =
  "ROUTE_TO_ADDITIONAL_PARAMETER_MASTER";
