export const ADD_EQUATION_SYMBOLS = "ADD_EQUATION_SYMBOLS";
export const ADD_TEXT_BODY_WITH_KEYPRESS = "ADD_TEXT_BODY_WITH_KEYPRESS";
export const ADD_PARAMETERS = "ADD_PARAMETERS";
export const POP_PARAMETERS = "POP_PARAMETERS";
