export const TOGGLE_TO_MASTER_TYPE_NAVIGATION =
  "TOGGLE_TO_MASTER_TYPE_NAVIGATION";
export const TOGGLE_TO_SAMPLE_TYPE_NAVIGATION =
  "TOGGLE_TO_SAMPLE_TYPE_NAVIGATION";
export const TOGGLE_TO_HOME_SCREEN_NAVIGATION =
  "TOGGLE_TO_HOME_SCREEN_NAVIGATION";
export const TOGGLE_TO_TEST_TRIALS_NAVIGATION =
  "TOGGLE_TO_TEST_TRIALS_NAVIGATION";
export const TOGGLE_TO_TEST_CONFIGURATION_NAVIGATION =
  "TOGGLE_TO_TEST_CONFIGURATION_NAVIGATION";
export const TOGGLE_TO_PRIVILEDGES_NAVIGATION =
  "TOGGLE_TO_PRIVILEDGES_NAVIGATION";
export const TOGGLE_TO_TEST_RESULTS_NAVIGATION =
  "TOGGLE_TO_TEST_RESULTS_NAVIGATION";
export const TOGGLE_TO_MIX_DESIGN_NAVIGATION =
  "TOGGLE_TO_MIX_DESIGN_NAVIGATION";
export const TOGGLE_TO_DASHBOARD_NAVIGATION = "TOGGLE_TO_DASHBOARD_NAVIGATION";
export const CHECK_WHETHER_REFRESH_NAVIGATION =
  "CHECK_WHETHER_REFRESH_NAVIGATION";
