export const ROUTE_TO_RAW_MATERIAL_TEST_RESULTS =
  "ROUTE_TO_RAW_MATERIAL_TEST_RESULTS";
export const ROUTE_TO_FINISH_PRODUCT_TEST_RESULTS =
  "ROUTE_TO_FINISH_PRODUCT_TEST_RESULTS";

// Toggle Finish Product Drawer
export const TOGGLE_FINISH_PRODUCT_DRAWER = "TOGGLE_FINISH_PRODUCT_DRAWER";
// Close Finish Product Drawer
export const CLOSE_FINISH_PRODUCT_DRAWER = "CLOSE_FINISH_PRODUCT_DRAWER";
